{% set name = "libcppitertools" %}
{% set version = "2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ryanhaining/cppitertools/archive/refs/tags/v{{ version }}.tar.gz
    sha256: f7bcd4531e37083609bb92c3f0ae03b56e7197002d0dc9c695104dcef445f2ab

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja

test:
  commands:
    - test -f $PREFIX/share/cppitertools/cppitertools-config.cmake  # [unix]
    - if not exist %PREFIX%\\Library\\share\\cppitertools\\cppitertools-config.cmake exit 1  # [win]
    - test -f $PREFIX/include/cppitertools/itertools.hpp  # [unix]
    - if not exist %LIBRARY_INC%\\cppitertools\\itertools.hpp exit 1  # [win]

about:
  home: https://github.com/ryanhaining/cppitertools
  license: BSD-2-Clause
  license_file: LICENSE.md
  summary: Implementation of python itertools and builtin iteration functions for C++17.

extra:
  feedstock-name: cppitertools
  recipe-maintainers:
    - traversaro
